### ISSUE TITLE
add in-repo changelog for stonesense

### ISSUE THREAD

**Issue by myk002** [DFHack/stonesense#117]
- [x] move existing `Changelog.txt` somewhere else in the repo for the historical record (and probably rename it, possibly change it to rst so it's contents get rendered)
- [x] create new `changelog.txt` in the format used by the other repos (`dfhack`, `scripts`, `df-structures`)
- [x] hook up processing of that new changlog to our documentation system (`gen_changelog.py`)
- [x] add docs verification to CI for the `stonesense` repo
- [x] update the release process on the wiki to include updating the changelog for new versions

**Comment by realSquidCoder** [comment]
Perhaps rename the old changelog to `historic_changelog.rst` or similar? I can try starting a new changelog at least if someone thinks its a good idea.

**Comment by realSquidCoder** [comment]
Perhaps rename the old changelog to `historic_changelog.rst` or similar? I can try starting a new changelog at least if someone thinks its a good idea.

**Comment by myk002** [comment]
The main repo has a https://docs.dfhack.org/en/stable/docs/about/History.html#history page where the older changelogs live. We can have a similar page in `stonesense/`
