### ISSUE TITLE
[feature request] cut away obsuring walls

### ISSUE THREAD

**Issue by ewtoombs** [DFHack/stonesense#37]
In Diablo II, III, and some other games, obscuring walls are cut away, leaving a sort of symbolic "curb" where the wall is. Stonesense has something similar, but the back walls are cut away too, when they could be left intact. I just think it looks better with the back walls intact.

**Comment by JapaMala** [comment]
Pressing C cycles between cutting everything, cutting in front of buildings and people, and cutting in front of just peope. Feature is already there. Issue closed.

**Comment by lethosor** [comment]
Worth noting that this doesn't work on OS X due to #32
