### ISSUE TITLE
Improve documentation for Stonesense

### ISSUE THREAD

**Issue by PeridexisErrant** [DFHack/stonesense#42]
The Stonesense readme isn't particularly comprehensive, and parts are certainly out of date.  It would be good to write more comprehensive docs, like the new DFHack documentation.  I'll try to get to this sometime, but probably not before a couple of DF releases.  If done appropriately, it could be integrated in the same way as the df-structures docs on https://dfhack.readthedocs.org

Related to DFHack/dfhack#648

**Comment by JapaMala** [comment]
Yeah, documentation's something I'm really bad at, though I'd also eventually like to do something similar for Armok Vision.

**Comment by PeridexisErrant** [comment]
No worries, I'm happy to write the docs.  

I'm thinking of adapting the wiki pages on [Stonesense](http://dwarffortresswiki.org/index.php/Utility:Stonesense) and [Adding content](http://dwarffortresswiki.org/index.php/Utility:Stonesense/Adding_Content), and linking to the content repository.  Could you skim those pages and let me know if they're up to date, or what's changed?
