### ISSUE TITLE
Can't change the colored dwarf tile set

### ISSUE THREAD

**Issue by Equilibrium94** [DFHack/stonesense#66]
I would like to replace the /creatures/color_Dwarves.png with the dwarves in creatres/dwarves.png. In /creatures/index.txt
I try to comment out color_Dwarves and remove the comment from Dwarves.xml like this:

#color_Dwarves.xml
Dwarves.xml

However, the colored dwarves still appear when running the game

**Comment by lethosor** [comment]
Not sure if comments are supported. Can you try removing the line entirely?

**Comment by Equilibrium94** [comment]
I had to remove the large_x folders to get it to work!
