### ISSUE TITLE
Windows 10 : Stonesense crashes when resizing window

### ISSUE THREAD

**Issue by jeancallisti** [DFHack/stonesense#69]
Note: I have dual screens but I don't know if it's related.

**Scenario :**
- Start DF with DFHack
- Start stonesense.
**- You can resize stonesense window as long as it's in the splash screen**
- Load a saved game
- stonesense redraws the scene and everything works : scroll, change Z, etc.
- With the mouse, maximize the stonesense window or simply resize it by dragging the corners (enlarge size or reduce size)
**Expected :** The window gets resized properly
**Observed (Faulty) :** Stonesense raises an exception (and crashes)

**Details :** 
- The exception happens deep inside d3d9.dll

`Unhandled exception at 0x00007FF8ACC54C15 (d3d9.dll) in Dwarf Fortress.exe: 0xC0000005: Access violation reading location 0x0000000000000088.
`

The call stack is : 

        d3d9.dll!00007ff8acc54c15()	Unknown
        d3d9.dll!00007ff8acd3d59f()	Unknown
        d3d9.dll!00007ff8acd26993()	Unknown
        d3d9.dll!00007ff8acd188bd()	Unknown
        stonesense.plug.dll!_al_d3d_prepare_for_reset(struct ALLEGRO_DISPLAY_D3D *)	Unknown
        stonesense.plug.dll!_al_d3d_update_render_state()	Unknown
        stonesense.plug.dll!_al_d3d_update_render_state()	Unknown
        stonesense.plug.dll!al_set_clipping_rectangle()	Unknown
        stonesense.plug.dll!al_set_clipping_rectangle()	Unknown
        stonesense.plug.dll!al_draw_tinted_scaled_bitmap()	Unknown
        stonesense.plug.dll!WorldSegment::DrawAllTiles() Line 292	C++
        stonesense.plug.dll!paintboard() Line 1146	C++
        stonesense.plug.dll!main_loop(ALLEGRO_DISPLAY * display, Overlay * ovrlay, ALLEGRO_EVENT_QUEUE * queue, ALLEGRO_THREAD * main_thread, DFHack::color_ostream & con) Line 302	C++
        stonesense.plug.dll!stonesense_thread(ALLEGRO_THREAD * main_thread, void * parms) Line 558	C++

The exception happens while calling this stonesense code : 

    al_draw_tinted_scaled_bitmap(
        (ALLEGRO_BITMAP*) todraw[i].drawobject,
        todraw[i].tint,
        todraw[i].sx,
        todraw[i].sy,
        todraw[i].sw,
        todraw[i].sh,
        todraw[i].dx,
        todraw[i].dy,
        todraw[i].dw,
        todraw[i].dh,
        todraw[i].flags );

Please note : there doesn't seem to be any issue with any of the fields of todraw. Allegro compains internally, inside the Direct3D primitive. Maybe because it's drawing outside of the screen? The issue still happens when _enlarging_ the window.

**Comment by Nekkowe** [comment]
I have the same issue in the current release, including being able to resize just fine in the splash screen but not outside of it.

**Comment by lethosor** [comment]
Consolidating with #38
