### ISSUE TITLE
Stonesense crash as soon as a game load.

### ISSUE THREAD

**Issue by r4d6** [DFHack/stonesense#74]
I start DF 0.47.04, but as soon as I load a game, both Stonesense and DF crash.

I am using LazyNewbPack.

Same issue as in https://github.com/DFHack/stonesense/issues/68 , however it said to reopen another issue if it still happened, so I did.

**Comment by r4d6** [comment]
I'm on Windows 10, and the starter pack is '0.47.04-r10', at least according to the .zip file.

**Comment by lethosor** [comment]
Ok, "0.47.04-r3" is probably the DFHack version, then (it's printed in the DFHack console on startup, as well as on the title screen, or you can find it by running "help").

Reports of this on Windows tend to be a bit less common - does this happen with every save on your end (even a new one) or just a particular save?

**Comment by r4d6** [comment]
actually, it looks like it is r1, which I am surprised about, considering that the PeridexisErrant's Starter Pack that I'm using was updated 6 days ago.

**Comment by lethosor** [comment]
Can you run "install-info" and upload the file it produces here?

**Comment by r4d6** [comment]
[install-info.txt](https://github.com/DFHack/stonesense/files/5547324/install-info.txt)
Here you go

**Comment by lethosor** [comment]
Are you sure you're running 0.47.04-r10 of [this pack](https://dffd.bay12games.com/file.php?id=7622)? I just downloaded it and it has DFHack 0.47.04-r3 (and your log does indeed indicate DFHack 0.47.04-r1).

**Comment by r4d6** [comment]
... I know what happened now.

Since I didn't know what overwriting my DF file with the one present in the .zip file would do, I just unzipped the LNP file and the .exe.

But the hack is in the DF file. That I didn't touch. Because I feared it would mess with my save.

I extracted the whole file, and it worked without deleting my saves, which were probably not even located there.

Now it work fine, even if I have no idea how to use it.

**Comment by r4d6** [comment]
Nevermind it just crashed again.

**Comment by r4d6** [comment]
Though this time I could use it for a few seconds.

**Comment by lethosor** [comment]
Ok, that would explain why you were running r1.

Could you clarify what causes the new crash? Is it dragging in the stonesense window with the right mouse button or something else?

**Comment by r4d6** [comment]
Well, it crashed when I was moving with the right mouse button while trying to figure out how it worked. (The view inside Ssense, not the actual window). It was moving very fast in all direction as soon as I moved my mouse, and after a few seconds of moving everywhere constantly at high-speed, it crashed.

Also that was when it was as a separate window and not an overlay.

**Comment by lethosor** [comment]
I wasn't able to reproduce that, although I'm not quite sure what you mean by "moving everywhere constantly at high-speed". I held my right mouse button down, and managed to move the view to x=-15000 or so without a crash. Holding my right mouse button down and moving around in circles also doesn't seem to crash, at least not within a minute or so. Perhaps this is Windows-specific? In any case, we'd likely need some more specific reproduction steps to attempt to resolve this.

**Comment by r4d6** [comment]
Doesn't seem to happen to me either. Looks like it was a one-time thing.
