### ISSUE TITLE
[Linux] Stonesense crashes when using CTRL+Scroll to add or remove a z-layer

### ISSUE THREAD

**Issue by Bl4ckh34d** [DFHack/stonesense#81]
As mentioned in the title, stonesense crashes, when I try adding or removing a z-layer via CTRL+Scroll.
When it crashes, it takes DF with it as well as DFHack, so there is no way of getting any output.
Is there a error log somewhere?  This might be helpful.

OS: Ubuntu 20.04 64-Bit
Starter Kit:PyLNP 0.14a
DFHack: 0.47.05-r1

**Comment by lethosor** [comment]
Please try upgrading to DFHack 0.47.05-r2 - this sounds exactly like the issue that was fixed in #76 and #79.

**Comment by Bl4ckh34d** [comment]
Oh, I didn't see there is an updated version already. I got mine a couple of days ago from the official forum.
Thank you!

**Comment by Bl4ckh34d** [comment]
Can be closed, since it is already fixed. Thank you!

**Comment by lethosor** [comment]
Yeah, packs on the forum are not official, and aren't always up-to-date with the latest utilities (or even the latest DF). Anyway, thanks for reporting back so quickly, and glad it works now!
