### ISSUE TITLE
How to install with the steam version on Windows?

### ISSUE THREAD

**Issue by Sci3nce** [DFHack/stonesense#86]

**Comment by myk002** [comment]
Stonesense is a DFHack plugin. All DFHack plugins rely on DFHack to be installed, and the DFHack team has to reverse engineer the steam version and adjust the code to changes. In short, you can't install stonesense for the steam version of DF until DFHack has been released for the steam version of DF.

Once DFHack itself is ready, stonesense will have to be updated as well, and we don't have a timeline for that right now.

**Comment by quietust** [comment]
> Once DFHack itself is ready, stonesense will have to be updated as well, and we don't have a timeline for that right now.

In case you're looking for a rough estimate, the most likely release date for DFHack v(0.)50.xx will be _months_ from now.

**Comment by lethosor** [comment]
Stonesense is included in DFHack 50.05-alpha1
