### ISSUE TITLE
Stonesense mouse wheel z axis inversion option needed

### ISSUE THREAD

**Issue by agilmore2** [DFHack/stonesense#95]
DFHack/dfhack#2790 

If I wanted to add an option to stonesense to allow mouse wheel z axis inversion to stop bringing forward my patch and manually building it every time, would that step on anyone's toes?

Should it go in the init or the keybinds config files?

**Comment by lethosor** [comment]
I would say init as opposed to keybindings, assuming this option doesn't fit the schema of the keybindings file

**Comment by realSquidCoder** [comment]
this has been added for some time now afaik. can we close this issue?

**Comment by realSquidCoder** [comment]
i honestly dont know but i can confirm it exists in init.txt and works. i dont have time to go search the commits rn unfortunately

**Comment by realSquidCoder** [comment]
Found it! Yeah its been here for a bit
https://github.com/DFHack/stonesense/commit/ee12ed2ff19809bc6d7eb4a00537c61517dbc56a

**Comment by myk002** [comment]
Fixed in https://github.com/DFHack/stonesense/pull/97
